import { z } from "zod";

const artifactStorageKindSchema = z.enum([
  "local_file",
  "object_storage",
  "db_blob",
  "external_url",
]);

export const artifactRefSchema = z.object({
  ref_id: z.string().min(1),
  uri: z.string().min(1),
  storage_kind: artifactStorageKindSchema,
  content_type: z.string().min(1),
  byte_size: z.number().int().nonnegative().nullable().optional(),
  sha256: z.string().min(1).nullable().optional(),
});

const jsonValueSchema: z.ZodType<unknown> = z.lazy(() =>
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    z.null(),
    z.array(jsonValueSchema),
    z.record(z.string(), jsonValueSchema),
  ]),
);

export const evidenceHandoffReadinessSchema = z.enum(["alta", "media", "baja", "blocked"]);
export const evidenceHandoffQualityStatusSchema = z.enum(["pass", "warn", "blocked"]);

export const evidenceEngineHandoffV1Schema = z.object({
  handoff_id: z.string().min(1),
  handoff_version: z.literal("evidence_engine_handoff.v1"),
  project_id: z.string().min(1),
  evidence_run_id: z.string().min(1),
  created_at: z.string().min(1),
  source_engine: z.literal("EvidenceEngine"),
  source_engine_version: z.string().min(1),
  artifact_hash: z.string().min(1),
  readiness: evidenceHandoffReadinessSchema,
  quality_gate: z.object({
    status: evidenceHandoffQualityStatusSchema,
    warnings: z.array(z.string()),
    blockers: z.array(z.string()),
  }),
  warnings: z.array(z.string()),
  source_snapshot: z.array(artifactRefSchema),
  project_context: z.object({
    language: z.literal("es"),
    country_context: z.string().min(1),
    degree_level: z.string().min(1),
    target_template_key: z.string().nullable().optional(),
    master_template_key: z.literal("MASTER_TEMPLATE_LATAM"),
    topic: z.string().min(1),
    problem_context: z.string().nullable().optional(),
    research_line: z.string().nullable().optional(),
    methodology_preference: z.string().nullable().optional(),
    population_or_context: z.string().nullable().optional(),
    constraints: z.string().nullable().optional(),
    academic_program: z.string().nullable().optional(),
    university: z.string().nullable().optional(),
    advisor_or_user_notes: z.string().nullable().optional(),
    normalized_problem_core: z.string().nullable().optional(),
    retrieval_brief: z.string().nullable().optional(),
  }),
  source_registry: z.array(
    z.object({
      source_id: z.string().min(1),
      reference_id: z.string().nullable(),
      title: z.string().min(1),
      authors: z.array(z.string()),
      year: z.number().int().nullable(),
      venue: z.string().nullable(),
      doi: z.string().nullable(),
      landing_page_url: z.string().nullable(),
      pdf_url: z.string().nullable(),
      openalex_id: z.string().nullable(),
      crossref_id: z.string().nullable(),
      is_open_access: z.boolean(),
      selected_order: z.number().int().nullable(),
      eligible_for_formal_reference: z.boolean(),
      citation_metadata: z.object({
        citation_key: z.string().nullable().optional(),
        apa7: z.string().nullable().optional(),
        bibtex: z.string().nullable().optional(),
        ris: z.string().nullable().optional(),
        raw: jsonValueSchema.optional(),
      }),
      materialization_refs: z.object({
        extracted_text_refs: z.array(artifactRefSchema),
        chunk_refs: z.array(artifactRefSchema),
        pdf_refs: z.array(artifactRefSchema),
        derived_asset_refs: z.array(artifactRefSchema),
      }),
    }),
  ),
  evidence_units: z.array(
    z.object({
      evidence_id: z.string().min(1),
      source_id: z.string().min(1),
      unit_type: z.enum([
        "original_excerpt",
        "table",
        "image",
        "equation",
        "interpreted_signal",
        "context_only",
      ]),
      section_keys: z.array(z.string()),
      label: z.string().min(1),
      original_text: z.string().nullable(),
      summary_es: z.string().nullable(),
      page_start: z.number().int().nullable(),
      page_end: z.number().int().nullable(),
      char_start: z.number().int().nullable(),
      char_end: z.number().int().nullable(),
      quote_hash: z.string().nullable(),
      asset_key: z.string().nullable().optional(),
      asset_ref: artifactRefSchema.nullable().optional(),
      caption: z.string().nullable().optional(),
      original_language: z.string().nullable(),
      citation_eligibility: z.enum([
        "direct_quote",
        "paraphrase_only",
        "asset_reference",
        "not_citable",
      ]),
      confidence: z.number(),
      relevance_score: z.number(),
      claim_scope: z.enum([
        "source_fact",
        "method_context",
        "theoretical_context",
        "background_context",
        "assumption_only",
        "do_not_claim",
      ]),
    }),
  ),
  section_packets: z.array(
    z.object({
      section_key: z.string().min(1),
      readiness: evidenceHandoffReadinessSchema,
      summary: z.string().nullable(),
      source_ids: z.array(z.string()),
      snippet_ids: z.array(z.string()),
      evidence_ids: z.array(z.string()),
      asset_keys: z.array(z.string()),
      key_points: z.array(z.string()),
      open_questions: z.array(z.string()),
      missing_elements: z.array(z.string()),
      do_not_claim: z.array(z.string()),
      assumptions_allowed: z.array(z.string()),
      recommended_chunk_refs: z.array(artifactRefSchema),
      required_original_fragments: z.array(z.string()),
    }),
  ),
  weak_section_packets: z.array(z.unknown()),
  source_priorities: z.array(jsonValueSchema),
  asset_registry: z.array(
    z.object({
      asset_key: z.string().min(1),
      source_id: z.string().min(1),
      asset_kind: z.enum(["figure", "image", "table", "equation"]),
      title: z.string().nullable(),
      caption: z.string().nullable(),
      page_number: z.number().int().nullable(),
      text_content: z.string().nullable(),
      latex: z.string().nullable().optional(),
      file_ref: artifactRefSchema.nullable(),
      mime_type: z.string().nullable(),
      width_px: z.number().int().nullable(),
      height_px: z.number().int().nullable(),
      content_hash: z.string().nullable(),
      extraction_origin: z.enum(["pdf_native", "llm_reconstructed", "provider_metadata"]),
      citation_eligibility: z.enum([
        "direct_quote",
        "paraphrase_only",
        "asset_reference",
        "not_citable",
      ]),
      recommended_section_keys: z.array(z.string()),
      usage_reason: z.string().nullable(),
      handling_notes: z.array(z.string()),
    }),
  ),
  asset_usage_plan: z.array(jsonValueSchema),
  materialized_content_refs: z.array(artifactRefSchema),
  chunk_index_refs: z.array(artifactRefSchema),
  proposal_context: z.object({
    method_candidate: jsonValueSchema,
    framework_candidate: jsonValueSchema,
    dominant_methods: z.array(jsonValueSchema),
    dominant_frameworks: z.array(jsonValueSchema),
    key_findings: z.array(jsonValueSchema),
    evidence_gaps: z.array(z.string()),
    followup_requirements: jsonValueSchema,
    gap_resolution_plan: jsonValueSchema,
    context_preservation_contract: jsonValueSchema.optional(),
  }),
  assumptions: z.array(
    z.object({
      assumption_id: z.string().min(1),
      statement: z.string().min(1),
      reason: z.string().min(1),
      section_keys: z.array(z.string()),
    }),
  ),
  traceability: z.object({
    source_artifacts: z.array(artifactRefSchema),
    immutable_snapshot_hash: z.string().min(1),
  }),
});

