import type { SupportedLanguage } from "@/lib/language";

type StatusTone = "plum" | "lilac" | "gold" | "mint" | "blush" | "slate";

export type ProjectStatusMeta = {
  label: string;
  summary: string;
  nextStep: string;
  stage: number;
  tone: StatusTone;
};

const STATUS_META: Record<SupportedLanguage, Record<string, ProjectStatusMeta>> = {
  es: {
    DRAFT: {
      label: "Base por definir",
      summary: "Todavia falta convertir la idea inicial en un intake utilizable.",
      nextStep: "Completa el intake para dejar lista la base del proyecto.",
      stage: 1,
      tone: "lilac",
    },
    INTAKE_READY: {
      label: "Intake listo",
      summary: "La base del proyecto ya permite buscar fuentes iniciales.",
      nextStep: "Ejecuta la busqueda y filtra fuentes semilla trazables.",
      stage: 2,
      tone: "gold",
    },
    SEARCHING: {
      label: "Buscando fuentes",
      summary: "Ingeniometrix esta consultando OpenAlex y Crossref.",
      nextStep: "Espera los resultados y selecciona las referencias mas utiles.",
      stage: 2,
      tone: "gold",
    },
    SOURCES_REVIEW: {
      label: "Fuentes en revision",
      summary: "Ya hay referencias cargadas, pero aun falta elegir el set semilla.",
      nextStep: "Guarda una seleccion corta y representativa para continuar.",
      stage: 2,
      tone: "gold",
    },
    SOURCES_SELECTED: {
      label: "Fuentes seleccionadas",
      summary: "El proyecto ya tiene evidencia suficiente para generar un blueprint.",
      nextStep: "Genera el blueprint para validar coherencia y trazabilidad.",
      stage: 3,
      tone: "mint",
    },
    BLUEPRINT_GENERATING: {
      label: "Generando blueprint",
      summary: "Ingeniometrix esta estructurando el plan con las fuentes elegidas.",
      nextStep: "Revisa el resultado apenas termine la generacion.",
      stage: 3,
      tone: "mint",
    },
    BLUEPRINT_READY: {
      label: "Blueprint listo",
      summary: "Ya tienes una version estructurada del plan con reporte de coherencia.",
      nextStep: "Revisa faltantes, supuestos y prepara la exportacion.",
      stage: 4,
      tone: "plum",
    },
    EXPORT_READY: {
      label: "Listo para exportar",
      summary: "El proyecto ya esta en una etapa final de salida y documentacion.",
      nextStep: "Exporta o revisa la version mas reciente antes de cerrar.",
      stage: 4,
      tone: "plum",
    },
    ARCHIVED: {
      label: "Archivado",
      summary: "Este proyecto se mantiene como referencia historica.",
      nextStep: "Reabre o crea uno nuevo si necesitas seguir trabajando.",
      stage: 4,
      tone: "slate",
    },
  },
  en: {
    DRAFT: {
      label: "Base pending",
      summary: "The initial idea still needs to become a usable intake.",
      nextStep: "Complete the intake so the project has a working base.",
      stage: 1,
      tone: "lilac",
    },
    INTAKE_READY: {
      label: "Intake ready",
      summary: "The project base is ready for initial source search.",
      nextStep: "Run the search and review traceable seed sources.",
      stage: 2,
      tone: "gold",
    },
    SEARCHING: {
      label: "Searching sources",
      summary: "Ingeniometrix is querying OpenAlex and Crossref.",
      nextStep: "Wait for results and select the most useful references.",
      stage: 2,
      tone: "gold",
    },
    SOURCES_REVIEW: {
      label: "Sources in review",
      summary: "References are loaded, but the seed set still needs to be selected.",
      nextStep: "Save a short representative source selection to continue.",
      stage: 2,
      tone: "gold",
    },
    SOURCES_SELECTED: {
      label: "Sources selected",
      summary: "The project has enough evidence to generate a blueprint.",
      nextStep: "Generate the blueprint to validate coherence and traceability.",
      stage: 3,
      tone: "mint",
    },
    BLUEPRINT_GENERATING: {
      label: "Generating blueprint",
      summary: "Ingeniometrix is structuring the plan with the selected sources.",
      nextStep: "Review the result as soon as generation finishes.",
      stage: 3,
      tone: "mint",
    },
    BLUEPRINT_READY: {
      label: "Blueprint ready",
      summary: "You have a structured plan version with a coherence report.",
      nextStep: "Review gaps, assumptions, and prepare the exports.",
      stage: 4,
      tone: "plum",
    },
    EXPORT_READY: {
      label: "Ready to export",
      summary: "The project is in the final output and documentation stage.",
      nextStep: "Export or review the latest version before closing.",
      stage: 4,
      tone: "plum",
    },
    ARCHIVED: {
      label: "Archived",
      summary: "This project is kept as historical reference.",
      nextStep: "Reopen it or create a new one if you need to continue.",
      stage: 4,
      tone: "slate",
    },
  },
};

export function getProjectStatusMetaForLanguage(
  status: string,
  language: SupportedLanguage,
): ProjectStatusMeta {
  return (
    STATUS_META[language][status] ?? {
      label: status,
      summary:
        language === "en"
          ? "This status is not classified yet."
          : "Estado no clasificado todavia.",
      nextStep:
        language === "en"
          ? "Review the project to continue."
          : "Revisa el proyecto para continuar.",
      stage: 1,
      tone: "slate",
    }
  );
}

export function getProjectUiCopy(language: SupportedLanguage) {
  return language === "en" ? EN_COPY : ES_COPY;
}

const ES_COPY = {
  action: {
    closeSession: "Salir",
    closingSession: "Saliendo...",
    pending: "Pendiente",
    ready: "Listo",
    downloadNow: "Descargar ahora",
  },
  workflow: {
    stepPrefix: "Paso",
    guidedFlow: "Flujo guiado",
    guidedFlowTitle: "Un solo camino, sin paneles innecesarios.",
    guidedFlowDescription:
      "Define el proyecto, completa el intake, selecciona fuentes y valida el blueprint. Todo lo demas queda fuera del MVP.",
    stages: {
      topic: ["Tema", "Idea semilla, variantes y seleccion de base tematica."],
      intake: ["Intake", "Problema, poblacion y contexto minimo del proyecto."],
      sources: ["Fuentes semilla", "Busqueda, revision y seleccion de evidencia trazable."],
      blueprint: ["Blueprint", "Validacion de coherencia y preparacion para salida."],
      export: ["Exportacion", "Salidas finales y evidencia lista para compartir."],
    },
  },
  projectPage: {
    description: "Avanza por etapas: intake, fuentes, blueprint y exportacion.",
    missingTopicKicker: "Falta cerrar la etapa tema",
    missingTopicTitle: "Antes del intake, elige la base tematica definitiva.",
    missingTopicBody:
      "Tu proyecto ya tiene semilla, pero aun no selecciona un tema final. Cierra esa etapa y luego sigue con intake, fuentes y blueprint.",
    goToTopic: "Ir a etapa Tema",
    currentStatus: "Estado actual",
    stageCounter: (stage: number) => `Etapa ${stage} de 5`,
    nextStep: "Siguiente paso",
    projectData: "Ver datos del proyecto",
    status: "Estado",
    university: "Universidad",
    degree: "Nivel",
    program: "Programa",
    template: "Plantilla",
    topicOrigin: {
      custom: "Idea propia",
      hybrid: "Idea propia + sugerencia",
      catalog: "Catalogo",
    },
    intakeKicker: "Intake estructurado",
    intakeTitle: "Construye una base mas clara para tu tesis.",
    intakeBody:
      "El objetivo aqui no es llenar un formulario administrativo, sino traducir tu idea en una estructura que luego podamos validar y enriquecer.",
  },
  intakeForm: {
    assistedKicker: "Intakes asistidos",
    noCatalogProject: "Proyecto sin catalogo relacionado",
    variants: "variantes",
    assistedBody:
      "Usa estas variantes como punto de partida editable. La meta no es copiar un ejemplo, sino aterrizar tu caso real con mayor rapidez.",
    tabHint: "Presiona Tab para autocompletar el campo actual con el intake activo.",
    generateFull: "Generar intake completo",
    anotherIntake: "Otro intake",
    nextIntake: "Siguiente intake",
    generating: "Generando...",
    draftApplied: (label: string) =>
      `Intake sugerido aplicado: ${label}. Puedes editarlo antes de guardar.`,
    draftError: "No se pudo generar un intake completo.",
    draftsGenerated: (count: number) => `Generamos ${count} intakes editables para este tema.`,
    draftUnavailable:
      "No se pudo generar el intake ahora. Puedes completar los campos manualmente.",
    saveError: "No se pudo guardar el intake.",
    saved: "Intake guardado correctamente.",
    quickKicker: "Minimo para avanzar",
    quickTitle: "Completa solo 3 campos y deja listo el paso de fuentes.",
    quickBody:
      "Para mover el proyecto no hace falta llenar todo ahora. Con tema, contexto del problema y poblacion objetivo ya podemos habilitar la siguiente etapa del flujo.",
    quickProgress: "Progreso rapido",
    quickReady: "Listo para guardar y pasar a fuentes.",
    quickMissing: "Aun faltan campos clave para habilitar la siguiente etapa.",
    presetLabel: "Variante de intake",
    noCatalogWithBase:
      "No encontramos una variante de catalogo para este proyecto, pero ya tienes una base sugerida editable en este intake.",
    noCatalogNoBase:
      "No encontramos una variante relacionada de catalogo para este proyecto. Puedes completar el intake manualmente o volver a la etapa Tema para generar otra base asistida.",
    keyStep: "Paso clave",
    keyTitle: "Deja la base minima del intake.",
    keyBody:
      "Este es el tramo mas importante para no perder impulso. Lo avanzado y opcional queda debajo para cuando ya tengas la base clara.",
    topic: "Tema",
    topicPlaceholder: "Describe el tema central de investigacion.",
    problemContext: "Contexto del problema",
    problemPlaceholder: "Explica el problema y por que importa.",
    targetPopulation: "Poblacion objetivo",
    populationPlaceholder: "Describe la poblacion o unidad de analisis.",
    expandedContext: "Contexto ampliado",
    expandedTitle: "Completa el resto solo si ya quieres afinar.",
    openAdvanced: "Abrir campos avanzados",
    expandedBody:
      "Aqui quedan linea de investigacion, metodologia, datos disponibles, restricciones y notas del asesor. Todo sigue disponible, pero ya no bloquea el avance inicial.",
    researchLine: "Linea de investigacion",
    methodology: "Metodologia preferida",
    availableData: "Datos disponibles",
    constraints: "Restricciones academicas",
    advisorNotes: "Observaciones del asesor",
    researchLinePlaceholder: "Ej. transformacion digital",
    methodologyPlaceholder: "Ej. enfoque mixto, cuantitativo, estudio de caso",
    dataPlaceholder: "Indica que datos o acceso real tienes.",
    constraintsPlaceholder: "Normas, alcance, observaciones formales o limites del programa.",
    advisorPlaceholder: "Pega aqui comentarios, requisitos o restricciones del asesor.",
    saving: "Guardando...",
    saveAndSources: "Guardar y pasar a fuentes",
    saveIntake: "Guardar intake",
    saveHint:
      "Cuando completas tema, contexto del problema y poblacion objetivo, el proyecto queda listo para buscar fuentes. Lo demas puede afinarse luego.",
  },
  contextRibbon: {
    kicker: "Contexto activo",
    title: "Todo lo importante del proyecto, visible desde el inicio.",
    body:
      "Este contexto define la base del MVP y sostiene las siguientes sugerencias dentro del workspace.",
    university: "Universidad",
    degree: "Nivel",
    program: "Programa",
    template: "Plantilla",
    seedIdea: "Idea semilla",
    activeTopic: "Tema activo",
    origin: "Origen",
  },
  sourceSearch: {
    kicker: "Fuentes bibliograficas",
    title: "Elige tus fuentes semilla.",
    body: (min: number, max: number) =>
      `Busca, revisa y guarda entre ${min} y ${max} referencias.`,
    search: "Buscar fuentes",
    searching: "Buscando...",
    completeIntake: "Completa intake minimo",
    intakeReady: "La base ya esta lista para buscar evidencia.",
    intakeMissing: "Falta completar tema, problema y poblacion para mejorar la busqueda.",
    selected: "Seleccionadas",
    showing: "Mostrando",
    of: "de",
    minimumIntakeInfo:
      "Completa primero el minimo del intake para que la busqueda tenga suficiente contexto.",
    searchError: "No se pudo ejecutar la busqueda.",
    referencesLoadError: "No se pudo cargar la lista de fuentes.",
    addedNew: (count: number) =>
      `Anadimos ${count} fuente(s) nueva(s) y mantuvimos tu seleccion actual.`,
    searchCompleted: (count: number, min: number, max: number) =>
      `Busqueda completada. Revisa las primeras ${count} fuentes y selecciona entre ${min} y ${max} referencias para continuar.`,
    noNew:
      "No encontramos referencias nuevas en este intento, pero mantuvimos las fuentes ya cargadas en el proyecto.",
    noResults:
      "No encontramos referencias con esta formulacion. Ajusta el intake o vuelve a intentar con un tema mas concreto.",
    maxSelected: (max: number) => `Puedes seleccionar hasta ${max} fuentes en esta etapa.`,
    saveRange: (min: number, max: number) =>
      `Debes seleccionar entre ${min} y ${max} fuentes para continuar.`,
    saveError: "No se pudo guardar la seleccion.",
    saved: "Seleccion de fuentes guardada.",
    contextSummary: "Ver contexto de busqueda",
    topic: "Tema",
    problemContext: "Contexto del problema",
    targetPopulation: "Poblacion objetivo",
    derivedQuery: "Consulta derivada",
    planner: "Planificador",
    llm: "LLM",
    fallbackPlanner: "Planificador heuristico",
    providers: "Proveedores",
    providerWarnings: "Avisos de proveedor",
    necessary: "Necesarias",
    complementary: "Complementarias",
    optional: "No obligatorias",
    noOptional: "Sin grupo opcional para esta corrida.",
    attemptedQueries: "Consultas intentadas",
    scoreRules: "Reglas de puntaje",
    scoreRuleItems: [
      "ALTO: coincide con grupos necesarios y complementarios.",
      "MEDIO: coincide solo con grupos necesarios.",
      "MINIMO: coincide solo con grupos opcionales.",
      "La recencia suma peso, pero anos futuros y placeholders se descartan.",
    ],
    variantJoiner: "o",
    emptyTitle: "Aun no hay referencias cargadas.",
    emptyBody:
      "Guarda un intake suficiente y ejecuta la busqueda. Si sigue vacio, prueba con un tema menos largo o mas especifico.",
    selectedOrder: (order: number) => `Seleccion ${order}`,
    notSelected: "No seleccionada",
    noDate: "Sin fecha",
    translated: "Traducida",
    abstractLabel: "Resumen",
    viewSource: "Ver fuente",
    pdfLabel: "PDF",
    details: "Ver detalles",
    unavailable: "No disponible",
    doiLabel: "DOI",
    scoreLabel: "Etiqueta de puntaje",
    queryLabel: "Consulta",
    stage: "Etapa",
    stageNecessary: "Necesarias",
    stageComplementary: "Necesarias + complementaria",
    stageBackup: "Backup opcional",
    necessaryMatches: "Match necesarias",
    complementaryMatches: "Match complementarias",
    optionalMatches: "Match opcionales",
    noStrongMatch: "Sin match fuerte",
    noBoost: "Sin refuerzo",
    noMatch: "Sin match",
    recency: "Recencia",
    pdfAccessible: "PDF accesible",
    yes: "Si",
    notVerified: "No verificado",
    originalTitle: "Titulo original",
    originalAbstract: "Resumen original disponible en el registro recuperado.",
    seeMore: (count: number) => `Ver ${count} mas`,
    searchMore: (count: number) => `Buscar ${count} mas`,
    loading: "Cargando...",
    saveHint: "Guarda la seleccion para continuar al blueprint.",
    saveSelection: "Guardar seleccion",
    saving: "Guardando...",
  },
  blueprint: {
    kicker: "Blueprint de investigacion",
    title: "Genera el blueprint.",
    body: "Usa tu intake y las fuentes elegidas para construir una primera version trazable.",
    generating: "Generando...",
    generate: "Generar blueprint",
    retry: "Reintentar blueprint",
    downloadWord: "Descargar Word completo (Master Template)",
    interrupted: (count: number) =>
      `La generacion anterior quedo interrumpida. Puedes reintentar con ${count} fuente(s) seleccionada(s).`,
    readyToGenerate: (count: number) =>
      `Listo para generar. Tienes ${count} fuente(s) seleccionada(s).`,
    missingSources: "Completa intake minimo y guarda fuentes antes de generar el blueprint.",
    preparation: "Ver preparacion",
    checklist: "Checklist",
    currentStatus: "Estado actual",
    intakeBase: "Base minima del intake",
    intakeBaseReady: "Tema, problema y poblacion ya estan definidos.",
    intakeBaseMissing: "Completa el intake minimo antes de generar.",
    sourcesSelected: "Fuentes seleccionadas",
    sourcesDetail: (count: number, min: number, max: number) =>
      `${count} seleccionadas de ${min}-${max} necesarias.`,
    blueprintValidation: "Blueprint listo para validacion",
    blueprintReadyDetail: "El proyecto ya puede pasar a estructura y coherencia.",
    blueprintMissingDetail: "Todavia falta cerrar la etapa de fuentes.",
    projectStill: (label: string, min: number, max: number) =>
      `El proyecto aun esta en "${label}". Primero debes guardar entre ${min} y ${max} fuentes para habilitar la generacion.`,
    queued: "Iniciando generacion",
    generated: "Blueprint generado correctamente.",
    generateError: "No se pudo generar el blueprint.",
    completed: "Blueprint listo",
    progressDefault: "Generando blueprint",
    progressBody:
      "Etapas reales del motor: contexto, antecedentes, redaccion, validacion y cierre.",
    noVersionsTitle: "Aun no hay versiones generadas.",
    noVersionsBody:
      "Cuando generes el primer blueprint, aqui veras el objetivo general, la coherencia basica y la lista de referencias usadas.",
    currentVersion: "Version actual",
    version: "Version",
    generatedAt: "Generada el",
    executiveView: "Vista ejecutiva",
    specificObjectives: "Objetivos especificos",
    questions: "Preguntas",
    assumptions: "Supuestos",
    noAssumptions: "No se registraron supuestos en esta version.",
    engineAlerts: "Alertas del motor",
    keyAntecedents: "Ver antecedentes clave",
    technicalSolution: "Solucion tecnica",
    unresolvedGap: "Vacio pendiente",
    objectiveGuidance: "Guia para mejorar objetivos",
    referencesAndCoherence: "Ver referencias y coherencia",
    referencesUsed: "Referencias usadas",
    coherenceReport: "Reporte de coherencia",
    missingInfo: "Faltantes detectados",
    noMissing: "No se detectaron faltantes relevantes.",
    risks: "Riesgos",
    noRisks: "No se detectaron riesgos mayores en esta version.",
    coherenceLabels: {
      problemObjective: "Problema vs objetivo",
      objectiveQuestion: "Objetivos vs preguntas",
      objectiveMethod: "Objetivos vs metodo",
      populationMethod: "Poblacion vs metodo",
      techniqueAnalysis: "Tecnicas vs analisis",
      citationTraceability: "Trazabilidad de citas",
    },
  },
  export: {
    kicker: "Exportacion",
    title: "Descarga tus archivos.",
    body:
      "Cuando el blueprint esta listo, puedes exportar el documento y los archivos de soporte.",
    downloadDocx: "Descargar DOCX",
    soon: "Proximamente",
    ready: "El blueprint ya esta listo para exportar.",
    notReady: "Primero necesitas una version de blueprint para activar las descargas.",
    selectedSources: "Fuentes elegidas",
    selectedSourcesBody: "Referencias seleccionadas para sostener el flujo de salida.",
    activeVersion: "Version activa",
    activeVersionBody: "Ultimo blueprint listo para convertirse en salida documental.",
    traceability: "Trazabilidad visible",
    traceabilityBody: "Referencias usadas en la version mas reciente del blueprint.",
    enabledWhen: "Se habilita cuando",
    waiting: "Esperando blueprint",
    status: "Ver estado de exportacion",
    complete: "Listo",
    pending: "Pendiente",
    formats: {
      docx: [
        "DOCX",
        "Plan editable para revision academica y siguientes iteraciones.",
        "Blueprint disponible",
      ],
      bibtex: [
        "BibTeX",
        "Salida bibliografica para flujos tecnicos y gestores de referencias.",
        "Fuentes seleccionadas",
      ],
      ris: [
        "RIS",
        "Intercambio simple con gestores bibliograficos compatibles.",
        "Fuentes seleccionadas",
      ],
      evidence: [
        "evidence_log.json",
        "Registro trazable de fuentes, decisiones y supuestos del proceso.",
        "Trazabilidad consolidada",
      ],
    },
    readiness: {
      intake: [
        "Base estructurada",
        "Tema, problema y poblacion ya dejan al proyecto en una base utilizable.",
      ],
      sources: (count: number) => [
        "Fuentes seleccionadas",
        `Actualmente hay ${count} fuentes marcadas dentro del proyecto.`,
      ],
      blueprintReady: (version: number | null, createdAt: string | null) => [
        "Blueprint disponible",
        `Version ${version ?? "-"} generada${createdAt ? ` el ${createdAt}` : ""}.`,
      ],
      blueprintMissing: [
        "Blueprint disponible",
        "Todavia no existe una version generada para preparar las salidas.",
      ],
      downloadsReady: [
        "Descarga conectada",
        "DOCX, BibTeX, RIS y evidence_log ya pueden descargarse desde esta misma etapa.",
      ],
      downloadsMissing: [
        "Descarga conectada",
        "Las salidas documentales aun no estan listas para descargarse.",
      ],
    },
  },
};

const EN_COPY: typeof ES_COPY = {
  action: {
    closeSession: "Exit",
    closingSession: "Exiting...",
    pending: "Pending",
    ready: "Ready",
    downloadNow: "Download now",
  },
  workflow: {
    stepPrefix: "Step",
    guidedFlow: "Guided flow",
    guidedFlowTitle: "One path, no unnecessary panels.",
    guidedFlowDescription:
      "Define the project, complete the intake, select sources, and validate the blueprint. Everything else stays outside the MVP.",
    stages: {
      topic: ["Topic", "Seed idea, variants, and final topic selection."],
      intake: ["Intake", "Problem, population, and minimum project context."],
      sources: ["Seed sources", "Search, review, and select traceable evidence."],
      blueprint: ["Blueprint", "Coherence validation and output preparation."],
      export: ["Export", "Final files and evidence ready to share."],
    },
  },
  projectPage: {
    description: "Move through intake, sources, blueprint, and exports.",
    missingTopicKicker: "Topic stage still open",
    missingTopicTitle: "Choose the final topic base before the intake.",
    missingTopicBody:
      "Your project already has a seed, but it still needs a final topic. Close that stage and then continue with intake, sources, and blueprint.",
    goToTopic: "Go to Topic stage",
    currentStatus: "Current status",
    stageCounter: (stage: number) => `Stage ${stage} of 5`,
    nextStep: "Next step",
    projectData: "View project data",
    status: "Status",
    university: "University",
    degree: "Degree",
    program: "Program",
    template: "Template",
    topicOrigin: {
      custom: "Own idea",
      hybrid: "Own idea + suggestion",
      catalog: "Catalog",
    },
    intakeKicker: "Structured intake",
    intakeTitle: "Build a clearer foundation for your research project.",
    intakeBody:
      "The goal here is not to fill an administrative form, but to translate your idea into a structure we can validate and enrich.",
  },
  intakeForm: {
    assistedKicker: "Assisted intakes",
    noCatalogProject: "Project without related catalog",
    variants: "variants",
    assistedBody:
      "Use these variants as an editable starting point. The goal is not to copy an example, but to ground your real case faster.",
    tabHint: "Press Tab to autocomplete the current field with the active intake.",
    generateFull: "Generate full intake",
    anotherIntake: "Another intake",
    nextIntake: "Next intake",
    generating: "Generating...",
    draftApplied: (label: string) =>
      `Suggested intake applied: ${label}. You can edit it before saving.`,
    draftError: "Could not generate a complete intake.",
    draftsGenerated: (count: number) => `Generated ${count} editable intakes for this topic.`,
    draftUnavailable:
      "The intake could not be generated right now. You can complete the fields manually.",
    saveError: "Could not save the intake.",
    saved: "Intake saved successfully.",
    quickKicker: "Minimum to continue",
    quickTitle: "Complete only 3 fields and prepare the source step.",
    quickBody:
      "You do not need to fill everything to move the project forward. Topic, problem context, and target population are enough to unlock the next stage.",
    quickProgress: "Quick progress",
    quickReady: "Ready to save and move to sources.",
    quickMissing: "Key fields are still missing before the next stage can open.",
    presetLabel: "Intake variant",
    noCatalogWithBase:
      "No catalog variant was found for this project, but this intake already has an editable suggested base.",
    noCatalogNoBase:
      "No related catalog variant was found for this project. You can complete the intake manually or return to the Topic stage to generate another assisted base.",
    keyStep: "Key step",
    keyTitle: "Leave the minimum intake base ready.",
    keyBody:
      "This is the most important stretch to keep momentum. Advanced and optional fields stay below for when the base is clear.",
    topic: "Topic",
    topicPlaceholder: "Describe the central research topic.",
    problemContext: "Problem context",
    problemPlaceholder: "Explain the problem and why it matters.",
    targetPopulation: "Target population",
    populationPlaceholder: "Describe the population or unit of analysis.",
    expandedContext: "Expanded context",
    expandedTitle: "Complete the rest only if you want to refine now.",
    openAdvanced: "Open advanced fields",
    expandedBody:
      "Research line, methodology, available data, constraints, and advisor notes stay here. Everything remains available, but it no longer blocks the initial flow.",
    researchLine: "Research line",
    methodology: "Preferred methodology",
    availableData: "Available data",
    constraints: "Academic constraints",
    advisorNotes: "Advisor notes",
    researchLinePlaceholder: "E.g. digital transformation",
    methodologyPlaceholder: "E.g. mixed methods, quantitative, case study",
    dataPlaceholder: "Indicate what real data or access you have.",
    constraintsPlaceholder: "Rules, scope, formal observations, or program limits.",
    advisorPlaceholder: "Paste comments, requirements, or advisor constraints here.",
    saving: "Saving...",
    saveAndSources: "Save and move to sources",
    saveIntake: "Save intake",
    saveHint:
      "When topic, problem context, and target population are complete, the project is ready to search sources. Everything else can be refined later.",
  },
  contextRibbon: {
    kicker: "Active context",
    title: "Everything important about the project, visible from the start.",
    body:
      "This context defines the MVP base and supports the next suggestions inside the workspace.",
    university: "University",
    degree: "Degree",
    program: "Program",
    template: "Template",
    seedIdea: "Seed idea",
    activeTopic: "Active topic",
    origin: "Origin",
  },
  sourceSearch: {
    kicker: "Bibliographic sources",
    title: "Choose your seed sources.",
    body: (min: number, max: number) =>
      `Search, review, and save between ${min} and ${max} references.`,
    search: "Search sources",
    searching: "Searching...",
    completeIntake: "Complete minimum intake",
    intakeReady: "The base is ready to search for evidence.",
    intakeMissing: "Complete topic, problem, and population to improve the search.",
    selected: "Selected",
    showing: "Showing",
    of: "of",
    minimumIntakeInfo:
      "Complete the minimum intake first so the search has enough context.",
    searchError: "Could not run the search.",
    referencesLoadError: "Could not load the source list.",
    addedNew: (count: number) =>
      `Added ${count} new source(s) and kept your current selection.`,
    searchCompleted: (count: number, min: number, max: number) =>
      `Search complete. Review the first ${count} sources and select between ${min} and ${max} references to continue.`,
    noNew:
      "No new references were found in this attempt, but the existing project sources were kept.",
    noResults:
      "No references were found with this wording. Adjust the intake or try a more concrete topic.",
    maxSelected: (max: number) => `You can select up to ${max} sources at this stage.`,
    saveRange: (min: number, max: number) =>
      `You must select between ${min} and ${max} sources to continue.`,
    saveError: "Could not save the selection.",
    saved: "Source selection saved.",
    contextSummary: "View search context",
    topic: "Topic",
    problemContext: "Problem context",
    targetPopulation: "Target population",
    derivedQuery: "Derived query",
    planner: "Planner",
    llm: "LLM",
    fallbackPlanner: "Heuristic fallback",
    providers: "Providers",
    providerWarnings: "Provider warnings",
    necessary: "Necessary",
    complementary: "Complementary",
    optional: "Optional",
    noOptional: "No optional group for this run.",
    attemptedQueries: "Attempted queries",
    scoreRules: "Score rules",
    scoreRuleItems: [
      "HIGH: matches necessary and complementary groups.",
      "MEDIUM: matches necessary groups only.",
      "MINIMUM: matches optional groups only.",
      "Recency adds weight, but future years and placeholders are rejected.",
    ],
    variantJoiner: "or",
    emptyTitle: "No references loaded yet.",
    emptyBody:
      "Save a sufficient intake and run the search. If it is still empty, try a shorter or more specific topic.",
    selectedOrder: (order: number) => `Selection ${order}`,
    notSelected: "Not selected",
    noDate: "No date",
    translated: "Translated",
    abstractLabel: "Abstract",
    viewSource: "View source",
    pdfLabel: "PDF",
    details: "View details",
    unavailable: "Unavailable",
    doiLabel: "DOI",
    scoreLabel: "Score label",
    queryLabel: "Query",
    stage: "Stage",
    stageNecessary: "Necessary",
    stageComplementary: "Necessary + complementary",
    stageBackup: "Optional backup",
    necessaryMatches: "Necessary matches",
    complementaryMatches: "Complementary matches",
    optionalMatches: "Optional matches",
    noStrongMatch: "No strong match",
    noBoost: "No boost",
    noMatch: "No match",
    recency: "Recency",
    pdfAccessible: "Accessible PDF",
    yes: "Yes",
    notVerified: "Not verified",
    originalTitle: "Original title",
    originalAbstract: "Original abstract available in the recovered record.",
    seeMore: (count: number) => `View ${count} more`,
    searchMore: (count: number) => `Search ${count} more`,
    loading: "Loading...",
    saveHint: "Save the selection to continue to the blueprint.",
    saveSelection: "Save selection",
    saving: "Saving...",
  },
  blueprint: {
    kicker: "Research blueprint",
    title: "Generate the blueprint.",
    body: "Use your intake and selected sources to build a first traceable version.",
    generating: "Generating...",
    generate: "Generate blueprint",
    retry: "Retry blueprint",
    downloadWord: "Download full Word file (Master Template)",
    interrupted: (count: number) =>
      `The previous generation was interrupted. You can retry with ${count} selected source(s).`,
    readyToGenerate: (count: number) =>
      `Ready to generate. You have ${count} selected source(s).`,
    missingSources: "Complete the minimum intake and save sources before generating the blueprint.",
    preparation: "View preparation",
    checklist: "Checklist",
    currentStatus: "Current status",
    intakeBase: "Minimum intake base",
    intakeBaseReady: "Topic, problem, and population are already defined.",
    intakeBaseMissing: "Complete the minimum intake before generating.",
    sourcesSelected: "Selected sources",
    sourcesDetail: (count: number, min: number, max: number) =>
      `${count} selected out of ${min}-${max} required.`,
    blueprintValidation: "Blueprint ready for validation",
    blueprintReadyDetail: "The project can now move to structure and coherence.",
    blueprintMissingDetail: "The source stage still needs to be closed.",
    projectStill: (label: string, min: number, max: number) =>
      `The project is still in "${label}". Save between ${min} and ${max} sources first to enable generation.`,
    queued: "Starting generation",
    generated: "Blueprint generated successfully.",
    generateError: "Could not generate the blueprint.",
    completed: "Blueprint ready",
    progressDefault: "Generating blueprint",
    progressBody:
      "Real engine stages: context, antecedents, drafting, validation, and close.",
    noVersionsTitle: "No versions generated yet.",
    noVersionsBody:
      "When you generate the first blueprint, the general objective, basic coherence, and used references will appear here.",
    currentVersion: "Current version",
    version: "Version",
    generatedAt: "Generated on",
    executiveView: "Executive view",
    specificObjectives: "Specific objectives",
    questions: "Questions",
    assumptions: "Assumptions",
    noAssumptions: "No assumptions were recorded in this version.",
    engineAlerts: "Engine alerts",
    keyAntecedents: "View key antecedents",
    technicalSolution: "Technical solution",
    unresolvedGap: "Unresolved gap",
    objectiveGuidance: "Guidance to improve objectives",
    referencesAndCoherence: "View references and coherence",
    referencesUsed: "References used",
    coherenceReport: "Coherence report",
    missingInfo: "Detected gaps",
    noMissing: "No relevant gaps were detected.",
    risks: "Risks",
    noRisks: "No major risks were detected in this version.",
    coherenceLabels: {
      problemObjective: "Problem vs objective",
      objectiveQuestion: "Objectives vs questions",
      objectiveMethod: "Objectives vs method",
      populationMethod: "Population vs method",
      techniqueAnalysis: "Techniques vs analysis",
      citationTraceability: "Citation traceability",
    },
  },
  export: {
    kicker: "Export",
    title: "Download your files.",
    body:
      "When the blueprint is ready, you can export the document and support files.",
    downloadDocx: "Download DOCX",
    soon: "Coming soon",
    ready: "The blueprint is ready to export.",
    notReady: "You need a blueprint version first to activate downloads.",
    selectedSources: "Selected sources",
    selectedSourcesBody: "References selected to support the output flow.",
    activeVersion: "Active version",
    activeVersionBody: "Latest blueprint ready to become a document output.",
    traceability: "Visible traceability",
    traceabilityBody: "References used in the latest blueprint version.",
    enabledWhen: "Enabled when",
    waiting: "Waiting for blueprint",
    status: "View export status",
    complete: "Ready",
    pending: "Pending",
    formats: {
      docx: [
        "DOCX",
        "Editable plan for academic review and next iterations.",
        "Blueprint available",
      ],
      bibtex: [
        "BibTeX",
        "Bibliographic output for technical workflows and reference managers.",
        "Sources selected",
      ],
      ris: [
        "RIS",
        "Simple exchange with compatible bibliography managers.",
        "Sources selected",
      ],
      evidence: [
        "evidence_log.json",
        "Traceable log of sources, decisions, and process assumptions.",
        "Traceability consolidated",
      ],
    },
    readiness: {
      intake: [
        "Structured base",
        "Topic, problem, and population make the project usable.",
      ],
      sources: (count: number) => [
        "Selected sources",
        `There are currently ${count} marked sources in the project.`,
      ],
      blueprintReady: (version: number | null, createdAt: string | null) => [
        "Blueprint available",
        `Version ${version ?? "-"} generated${createdAt ? ` on ${createdAt}` : ""}.`,
      ],
      blueprintMissing: [
        "Blueprint available",
        "No generated version exists yet for preparing outputs.",
      ],
      downloadsReady: [
        "Downloads connected",
        "DOCX, BibTeX, RIS, and evidence_log can be downloaded from this stage.",
      ],
      downloadsMissing: [
        "Downloads connected",
        "Document outputs are not ready to download yet.",
      ],
    },
  },
};
