import { MIN_SELECTED_USABLE_SOURCES, MAX_SELECTED_SOURCES } from "./source-sufficiency-policy";
export const MIN_SELECTED_REFERENCES = MIN_SELECTED_USABLE_SOURCES;
export const REFERENCE_BATCH_SIZE = 5;
export const MAX_SELECTED_REFERENCES = MAX_SELECTED_SOURCES;
