export const STEP5_SOURCE_EVIDENCE_EXTRACTION_PROMPT = {
  version: "ingeniometrix-step5-source-evidence-extraction-v1",
  storage: "filesystem_prompt_registry",
  systemPrompt:
    "Extract traceable academic evidence from the supplied text and metadata only. Never invent citations, page numbers, findings, methods, data, or equations. Use Spanish for user-facing fields.",
  userPromptTemplate: [
    "Extract reusable evidence for academic blueprint planning.",
    "",
    "Inputs:",
    "- final_intake_json: {{final_intake_json}}",
    "- section_content_plan_json: {{section_content_plan_json}}",
    "- source_registry_record_json: {{source_registry_record_json}}",
    "- evidence_basis: {{evidence_basis}}",
    "- recovered_chunks_json: {{recovered_chunks_json}}",
    "- asset_candidates_json: {{asset_candidates_json}}",
    "- source_health_json: {{source_health_json}}",
    "",
    "Return strict JSON with quality, methods/theories, variables/constructs, limitations, traceable evidence_items, asset_reviews, section_coverage, gaps, and warnings.",
    "",
    "Rules:",
    "- Every item must keep source_id, citation_key, reference_id, page_number when available, and chunk_id when available.",
    "- If evidence_basis is ABSTRACT_METADATA, allowed_use must be context_only or gap_only unless the abstract directly states a method.",
    "- Prefer methods, theories, variables, limitations, and assets useful for a thesis plan; avoid generic background.",
    "- Use section_key values exactly as supplied in section_content_plan_json.",
    "- If evidence is missing, return a gap.",
  ].join("\n"),
  outputSchema: {
    type: "object",
    additionalProperties: false,
    required: [
      "quality_score_100",
      "quality_decision",
      "technique_method_theory",
      "variables_or_constructs",
      "limitations",
      "evidence_items",
      "asset_reviews",
      "section_coverage",
      "gaps",
      "warnings",
    ],
    properties: {
      quality_score_100: { type: "number", minimum: 0, maximum: 100 },
      quality_decision: {
        type: "string",
        enum: ["sufficient_for_blueprint_preparation", "needs_more_evidence", "insufficient"],
      },
      technique_method_theory: {
        type: "array",
        maxItems: 8,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["label_es", "type", "description_es", "citation_anchor", "confidence_100"],
          properties: {
            label_es: { type: "string" },
            type: { type: "string", enum: ["technique", "method", "theory", "model", "concept"] },
            description_es: { type: "string" },
            citation_anchor: { $ref: "#/$defs/citation_anchor" },
            confidence_100: { type: "number", minimum: 0, maximum: 100 },
          },
        },
      },
      variables_or_constructs: {
        type: "array",
        maxItems: 8,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["name_es", "description_es", "role", "citation_anchor", "confidence_100"],
          properties: {
            name_es: { type: "string" },
            description_es: { type: "string" },
            role: { type: "string", enum: ["variable", "indicator", "parameter", "category", "metric"] },
            citation_anchor: { $ref: "#/$defs/citation_anchor" },
            confidence_100: { type: "number", minimum: 0, maximum: 100 },
          },
        },
      },
      limitations: {
        type: "array",
        maxItems: 6,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["limitation_es", "citation_anchor", "confidence_100"],
          properties: {
            limitation_es: { type: "string" },
            citation_anchor: { $ref: "#/$defs/citation_anchor" },
            confidence_100: { type: "number", minimum: 0, maximum: 100 },
          },
        },
      },
      evidence_items: {
        type: "array",
        maxItems: 12,
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "evidence_id",
            "source_id",
            "citation_key",
            "section_key",
            "claim_type",
            "traceable_summary_es",
            "supporting_quote_or_paraphrase_es",
            "citation_anchor",
            "confidence_100",
            "allowed_use",
            "gaps",
          ],
          properties: {
            evidence_id: { type: "string" },
            source_id: { type: "string" },
            citation_key: { type: "string" },
            section_key: { type: "string" },
            claim_type: { type: "string" },
            traceable_summary_es: { type: "string" },
            supporting_quote_or_paraphrase_es: { type: "string" },
            citation_anchor: { $ref: "#/$defs/citation_anchor" },
            confidence_100: { type: "number", minimum: 0, maximum: 100 },
            allowed_use: {
              type: "string",
              enum: ["blueprint_planning", "theory_or_method_support", "context_only", "gap_only"],
            },
            gaps: { type: "array", items: { type: "string" } },
          },
        },
      },
      asset_reviews: {
        type: "array",
        maxItems: 8,
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "asset_id",
            "source_id",
            "section_key",
            "relevance_score_100",
            "description_es",
            "keep_for_blueprint",
            "rendering_strategy",
            "citation_anchor",
          ],
          properties: {
            asset_id: { type: "string" },
            source_id: { type: "string" },
            section_key: { type: "string" },
            relevance_score_100: { type: "number", minimum: 0, maximum: 100 },
            description_es: { type: "string" },
            keep_for_blueprint: { type: "boolean" },
            rendering_strategy: {
              type: "string",
              enum: ["use_page_image_fallback", "needs_crop_or_reconstruction", "do_not_use"],
            },
            citation_anchor: { $ref: "#/$defs/citation_anchor" },
          },
        },
      },
      section_coverage: {
        type: "array",
        maxItems: 9,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["section_key", "coverage_score_100", "usable_evidence_ids", "gaps"],
          properties: {
            section_key: { type: "string" },
            coverage_score_100: { type: "number", minimum: 0, maximum: 100 },
            usable_evidence_ids: { type: "array", items: { type: "string" } },
            gaps: { type: "array", items: { type: "string" } },
          },
        },
      },
      gaps: { type: "array", items: { type: "string" } },
      warnings: { type: "array", items: { type: "string" } },
    },
    $defs: {
      citation_anchor: {
        type: "object",
        additionalProperties: false,
        required: ["citation_key", "reference_id", "source_id", "page_number", "chunk_id"],
        properties: {
          citation_key: { type: "string" },
          reference_id: { type: "string" },
          source_id: { type: "string" },
          page_number: { type: ["number", "null"] },
          chunk_id: { type: ["string", "null"] },
        },
      },
    },
  },
} as const;
