export const STEP6_EDITORIAL_REVIEW_PROMPT = {
  version: "ingeniometrix-step6-editorial-review-v1",
  storage: "filesystem_prompt_registry",
  systemPrompt: [
    "Eres un editor academico de Ingeniometrix.",
    "Tu tarea es realizar una correccion superficial de fluidez, ortografia, continuidad y estilo academico.",
    "Tambien debes comprimir el texto para respetar el presupuesto maximo de paginas.",
    "No agregues claims nuevos, datos nuevos, resultados nuevos, citas nuevas ni fuentes nuevas.",
    "Conserva las citas visibles y la trazabilidad existente.",
    "Conserva referencias cruzadas visibles a figuras, tablas, ecuaciones y matriz.",
    "No cambies tablas, figuras, ecuaciones ni referencias.",
    "Mantente en espanol academico sobrio.",
  ].join("\n"),
  userPromptTemplate: [
    "Revisa superficialmente las secciones narrativas del documento.",
    "",
    "STYLE_CONTRACT_JSON:",
    "{{style_contract_json}}",
    "",
    "PAGE_BUDGET_JSON:",
    "{{page_budget_json}}",
    "",
    "SECTION_SUMMARIES_JSON:",
    "{{section_summaries_json}}",
    "",
    "SECTIONS_JSON:",
    "{{sections_json}}",
    "",
    "Reglas:",
    "- Corrige fluidez, ortografia, repeticion y transiciones.",
    "- Reduce redundancia; prioriza precision academica sobre extension.",
    "- Mantén cada seccion dentro de su target_words cuando sea posible.",
    "- Conserva citation_label presentes en el texto.",
    "- Conserva menciones como Figura, Tabla, Ecuacion y Matriz si existen.",
    "- No agregues fuentes ni nuevas afirmaciones sustantivas.",
    "- Si una seccion ya esta bien, devuelvela sin cambios sustantivos.",
    "- Devuelve exclusivamente JSON valido.",
  ].join("\n"),
  outputSchema: {
    type: "object",
    additionalProperties: false,
    required: ["revised_sections", "notes", "warnings"],
    properties: {
      revised_sections: {
        type: "array",
        maxItems: 13,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["section_key", "paragraphs", "bullet_items", "revision_notes"],
          properties: {
            section_key: { type: "string" },
            paragraphs: {
              type: "array",
              maxItems: 12,
              items: { type: "string" },
            },
            bullet_items: {
              type: "array",
              maxItems: 12,
              items: { type: "string" },
            },
            revision_notes: {
              type: "array",
              maxItems: 6,
              items: { type: "string" },
            },
          },
        },
      },
      notes: {
        type: "array",
        maxItems: 12,
        items: { type: "string" },
      },
      warnings: {
        type: "array",
        maxItems: 12,
        items: { type: "string" },
      },
    },
  },
} as const;
