export const STEP6_SECTION_DRAFT_PROMPT = {
  version: "ingeniometrix-step6-section-draft-v1",
  storage: "filesystem_prompt_registry",
  systemPrompt: [
    "Eres Ingeniometrix, un asistente backend para investigacion academica responsable.",
    "Redacta una seccion editable para un documento Word academico usando exclusivamente el contexto provisto.",
    "No inventes citas, datos, resultados, autores, DOI, cifras ni evidencia.",
    "Si falta informacion, declarala como limitacion o supuesto.",
    "Mantente en espanol academico, profesional, claro y sobrio.",
    "No generes una tesis completa ni habilites fraude academico.",
    "Conserva trazabilidad hacia source_id, evidence_id, snippet_id y asset_key cuando aplique.",
    "Usa citas en el estilo solicitado mediante citation_label; no inventes autores ni referencias.",
    "Devuelve coordenadas de cita por parrafo y oracion para que el renderer inserte y audite las citas.",
  ].join("\n"),
  userPromptTemplate: [
    "Genera la seccion solicitada del blueprint editable.",
    "",
    "PROJECT_CONTEXT_JSON:",
    "{{project_context_json}}",
    "",
    "STYLE_CONTRACT_JSON:",
    "{{style_contract_json}}",
    "",
    "PAGE_BUDGET_JSON:",
    "{{page_budget_json}}",
    "",
    "SECTION_PLAN_JSON:",
    "{{section_plan_json}}",
    "",
    "GENERATION_WAVE:",
    "{{generation_wave}}",
    "",
    "EVIDENCE_ITEMS_JSON:",
    "{{evidence_items_json}}",
    "",
    "SOURCE_REGISTRY_JSON:",
    "{{source_registry_json}}",
    "",
    "ASSETS_JSON:",
    "{{assets_json}}",
    "",
    "PRIOR_SECTION_SUMMARIES_JSON:",
    "{{prior_section_summaries_json}}",
    "",
    "Reglas:",
    "- Respeta min_words y max_words del plan de seccion.",
    "- Escribe de forma compacta; el documento completo no debe exceder 15 paginas estimadas.",
    "- Usa solo los source_id, evidence_id, snippet_id y asset_key provistos.",
    "- Inserta citation_label en el texto donde corresponda y registra la misma cita en citation_anchors.",
    "- Cada afirmacion sustantiva basada en evidencia debe tener una citation_anchor.",
    "- Si la seccion contiene tablas/figuras/ecuaciones, redacta la narrativa que las introduce; los bloques nativos se renderizaran luego.",
    "- No cites fuentes no recuperadas.",
    "- No menciones metadatos internos, rutas, hashes, prompts ni quality gates.",
    "- Si la evidencia es insuficiente, redacta de forma prudente y marca limitaciones.",
    "- Devuelve exclusivamente JSON valido.",
  ].join("\n"),
  outputSchema: {
    type: "object",
    additionalProperties: false,
    required: [
      "section_key",
      "title",
      "paragraphs",
      "bullet_items",
      "used_source_ids",
      "used_evidence_ids",
      "used_snippet_ids",
      "used_asset_keys",
      "citation_anchors",
      "assumptions",
      "limitations",
      "warnings",
      "blocked",
    ],
    properties: {
      section_key: { type: "string" },
      title: { type: "string" },
      paragraphs: {
        type: "array",
        maxItems: 10,
        items: { type: "string" },
      },
      bullet_items: {
        type: "array",
        maxItems: 10,
        items: { type: "string" },
      },
      used_source_ids: {
        type: "array",
        items: { type: "string" },
      },
      used_evidence_ids: {
        type: "array",
        items: { type: "string" },
      },
      used_snippet_ids: {
        type: "array",
        items: { type: "string" },
      },
      used_asset_keys: {
        type: "array",
        items: { type: "string" },
      },
      citation_anchors: {
        type: "array",
        maxItems: 18,
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "paragraph_index",
            "sentence_index",
            "source_id",
            "evidence_id",
            "snippet_id",
            "citation_label",
            "claim_summary",
          ],
          properties: {
            paragraph_index: { type: "number", minimum: 0 },
            sentence_index: { type: ["number", "null"], minimum: 0 },
            source_id: { type: "string" },
            evidence_id: { type: ["string", "null"] },
            snippet_id: { type: ["string", "null"] },
            citation_label: { type: "string" },
            claim_summary: { type: "string" },
          },
        },
      },
      assumptions: {
        type: "array",
        maxItems: 8,
        items: { type: "string" },
      },
      limitations: {
        type: "array",
        maxItems: 8,
        items: { type: "string" },
      },
      warnings: {
        type: "array",
        maxItems: 8,
        items: { type: "string" },
      },
      blocked: { type: "boolean" },
    },
  },
} as const;
