export const STEP6_TITLE_GENERATION_PROMPT = {
  version: "ingeniometrix-step6-title-generation-v1",
  storage: "filesystem_prompt_registry",
  systemPrompt: [
    "Eres Ingeniometrix, un editor academico especializado en formulacion de titulos de investigacion.",
    "Genera un titulo profesional, preciso y defendible para un plan de tesis.",
    "Usa exclusivamente el intake, las secciones generadas y las fuentes recuperadas.",
    "No inventes poblacion, pais, institucion, metodologia, variables, resultados ni alcance no provisto.",
    "Evita titulos comerciales, grandilocuentes o demasiado generales.",
    "El titulo debe expresar objeto de estudio, relacion o enfoque principal, contexto si esta disponible y metodo si esta sustentado.",
  ].join("\n"),
  userPromptTemplate: [
    "Propón el titulo final del plan de tesis despues de revisar las secciones generadas.",
    "",
    "PROJECT_CONTEXT_JSON:",
    "{{project_context_json}}",
    "",
    "PAGE_BUDGET_JSON:",
    "{{page_budget_json}}",
    "",
    "SECTION_SUMMARIES_JSON:",
    "{{section_summaries_json}}",
    "",
    "SOURCE_REGISTRY_JSON:",
    "{{source_registry_json}}",
    "",
    "Reglas:",
    "- Titulo principal: maximo 26 palabras.",
    "- Titulo corto: maximo 12 palabras.",
    "- Debe sonar academico, sobrio y especifico.",
    "- Declara en warnings cualquier dato necesario que falte para hacer el titulo mas preciso.",
    "- Devuelve exclusivamente JSON valido.",
  ].join("\n"),
  outputSchema: {
    type: "object",
    additionalProperties: false,
    required: ["title", "short_title", "rationale", "keywords", "warnings"],
    properties: {
      title: { type: "string" },
      short_title: { type: "string" },
      rationale: { type: "string" },
      keywords: {
        type: "array",
        maxItems: 8,
        items: { type: "string" },
      },
      warnings: {
        type: "array",
        maxItems: 6,
        items: { type: "string" },
      },
    },
  },
} as const;
