export const STEP5_ASSET_VISUAL_LOCALIZATION_PROMPT = {
  version: "ingeniometrix-step5-asset-visual-localization-v1",
  storage: "filesystem_prompt_registry",
  systemPrompt:
    "Validate one academic PDF asset image and return a tight bounding box. Do not infer data or invent content.",
  userPromptTemplate: [
    "Locate the requested asset in the supplied image. The image may be a clean crop or a full-page fallback.",
    "",
    "Asset metadata:",
    "- asset_id: {{asset_id}}",
    "- source_id: {{source_id}}",
    "- asset_kind: {{asset_kind}}",
    "- page_number: {{page_number}}",
    "- caption_or_signal_text: {{caption_or_signal_text}}",
    "- semantic_description_es: {{semantic_description_es}}",
    "- intended_section_key: {{section_key}}",
    "",
    "Return strict JSON with localization_status, bbox_normalized, confidence_100, visual_description_es, and warnings.",
    "bbox_normalized uses decimals from 0 to 1: x, y, width, height.",
    "",
    "Rules:",
    "- Crop the actual asset, not the full page.",
    "- Include the caption only when it is visually attached to the asset.",
    "- Exclude page margins, unrelated paragraphs, headers, footers, and other assets.",
    "- If the asset cannot be uniquely identified, set localization_status to ambiguous or not_found.",
    "- If the asset is a table or equation, prefer legibility over ultra-tight margins.",
  ].join("\n"),
  outputSchema: {
    type: "object",
    additionalProperties: false,
    required: [
      "asset_id",
      "localization_status",
      "bbox_normalized",
      "confidence_100",
      "visual_description_es",
      "warnings",
    ],
    properties: {
      asset_id: { type: "string" },
      localization_status: { type: "string", enum: ["localized", "ambiguous", "not_found"] },
      bbox_normalized: {
        type: "object",
        additionalProperties: false,
        required: ["x", "y", "width", "height"],
        properties: {
          x: { type: "number", minimum: 0, maximum: 1 },
          y: { type: "number", minimum: 0, maximum: 1 },
          width: { type: "number", minimum: 0, maximum: 1 },
          height: { type: "number", minimum: 0, maximum: 1 },
        },
      },
      confidence_100: { type: "number", minimum: 0, maximum: 100 },
      visual_description_es: { type: "string" },
      warnings: { type: "array", items: { type: "string" } },
    },
  },
} as const;
