import assert from "node:assert/strict";
import { excerptOccurs, excerptSupportedAtAnchor, sourceDisposition } from "@/server/mvp/evidence-continuity";
import { buildEvidenceLog, extractExportReferences } from "@/server/blueprint/blueprint-export";
import { ledger } from "./test-b3-scientific-contracts";

const quote = "La observación permite identificar categorías sin anticipar resultados.";
assert.ok(excerptOccurs(quote, [quote.replace("identificar", "identi-\nficar")]));
assert.ok(!excerptOccurs(quote, ["La observación comprueba las categorías y demuestra resultados."]));
const chunks = [{ chunk_id: "S1-p001-c01", page_start: 1, page_end: 1, text: quote }];
assert.ok(excerptSupportedAtAnchor(quote, { chunk_id: chunks[0].chunk_id, page_number: 1 }, chunks));
assert.ok(!excerptSupportedAtAnchor(quote, { chunk_id: "S1-p002-c01", page_number: 2 }, chunks));
assert.ok(!excerptSupportedAtAnchor(quote, { chunk_id: chunks[0].chunk_id, page_number: 2 }, chunks));
assert.ok(!excerptSupportedAtAnchor(quote, { page_number: 1 }, [{ ...chunks[0], chunk_id: null, page_start: null, page_end: null }]));
const fixture = structuredClone(ledger);
fixture.semantic_extractions[0].reference_id = "R1";
fixture.semantic_extractions[0].source_id = "S1";
fixture.source_registry.push({ ...fixture.source_registry[0], source_id: "S2", reference_id: "R2" });
fixture.semantic_extractions.push({ ...structuredClone(fixture.semantic_extractions[0]), source_id: "S2", reference_id: "R2", evidence_items: [] });
fixture.source_registry.push({ ...fixture.source_registry[0], source_id: "S3", reference_id: "R3" });
const dispositions = sourceDisposition(fixture, ["S1"]);
assert.equal(dispositions.length, 3);
assert.deepEqual(dispositions.map((d) => d.exclusion_reason), [null, "NO_VERIFIED_NON_GAP_EVIDENCE", "EXTRACTION_NOT_RUN"]);
assert.throws(() => sourceDisposition(fixture, ["S2"]), /WITHOUT_SUPPORT/);
const version = { id: "fixture", versionNumber: 1, model: "fixture", promptVersion: "fixture", intakeSnapshotJson: {}, coherenceReportJson: {}, selectedReferencesSnapshotJson: fixture.source_registry, blueprintJson: { references_used: [{ reference_id: "R1" }], source_dispositions: dispositions } };
const log = buildEvidenceLog(version);
assert.equal(log.selectedReferences.length, 3);
assert.equal(log.consideredReferences?.length, 1);
assert.equal(log.excludedReferences?.length, 2);
assert.equal(log.referencesUsed.length, 1);
assert.equal(log.selectionSnapshotCompleteness, "COMPLETE");
assert.equal(extractExportReferences(version).length, 1);
assert.equal(extractExportReferences({ ...version, blueprintJson: { references_used: [] } }).length, 0);
assert.equal(extractExportReferences({ ...version, blueprintJson: {} }).length, 3);
assert.equal(buildEvidenceLog({ ...version, blueprintJson: {} }).selectionSnapshotCompleteness, "LEGACY_NOT_VERIFIED");
console.log("PASS RC4 evidence integrity: line-order normalization, exact anchors, explicit exclusion and reconciled selection (18 assertions).");
