import assert from "node:assert/strict";
import { assertEvidenceContinuity, evaluateEvidenceGate, excerptOccurs, inspectEvidenceLevel, inspectableEvidence, intakeFingerprint } from "@/server/mvp/evidence-continuity";
import type { MvpStep5EvidenceLedger } from "@/server/mvp/evidence-materialization-types";

const title = "Synthetic source for deterministic regression";
assert.equal(inspectEvidenceLevel({ title, text: "Recovered text", identity: "matched" }), "FULL_TEXT_MATERIALIZED");
assert.equal(inspectEvidenceLevel({ title, accessiblePdf: true }), "FULL_TEXT_AVAILABLE");
assert.equal(inspectEvidenceLevel({ title, abstract: "Inspectable abstract" }), "ABSTRACT_AVAILABLE");
assert.equal(inspectEvidenceLevel({ title }), "METADATA_ONLY");
assert.equal(inspectEvidenceLevel({ title: "" }), "UNUSABLE");
assert.equal(inspectEvidenceLevel({ title, abstract: "A valid abstract", identity: "mismatch" }), "UNUSABLE");
assert.ok(excerptOccurs("A long inspectable source excerpt.", ["First. A long inspectable source\nexcerpt. Last."]));
assert.equal(excerptOccurs("The source demonstrates invented findings.", ["No findings available."]), false);
const intake = { topic: "Fixture", preferredMethodology: "Diseno cuantitativo computacional" };
const ledger = { project_id: "fixture-project", step_run_id: "fixture-step", intake_fingerprint: intakeFingerprint(intake), source_registry: [{ reference_id: "fixture-ref" }], semantic_extractions: [] } as unknown as MvpStep5EvidenceLedger;
const context = { projectId: "fixture-project", stepRunId: "fixture-step", intake, referenceIds: ["fixture-ref"] };
assert.doesNotThrow(() => assertEvidenceContinuity(ledger, context));
assert.throws(() => assertEvidenceContinuity(ledger, { ...context, projectId: "other-project" }));
assert.throws(() => assertEvidenceContinuity(ledger, { ...context, stepRunId: "stale-run" }));
assert.throws(() => assertEvidenceContinuity(ledger, { ...context, intake: { ...intake, topic: "Changed" } }));
assert.throws(() => assertEvidenceContinuity(ledger, { ...context, referenceIds: ["different-ref"] }));
assert.equal(evaluateEvidenceGate(ledger).status, "INSUFFICIENT");
ledger.semantic_extractions = [{ status: "completed", evidence_basis: "PDF_FULLTEXT", evidence_items: [{ traceable_summary_es: "Extracto respaldado", allowed_use: "context_only", support_verified: true }] }] as any;
assert.equal(evaluateEvidenceGate(ledger).status, "SUFFICIENT");
ledger.semantic_extractions[0].evidence_basis = "ABSTRACT_METADATA";
assert.equal(evaluateEvidenceGate(ledger).status, "LIMITED");
// Paradigm changes neither require hypotheses nor authorize unsupported evidence.
const qualitative = { topic: "Fixture", preferredMethodology: "Estudio cualitativo interpretativo" };
assert.doesNotThrow(() => assertEvidenceContinuity({ ...ledger, intake_fingerprint: intakeFingerprint(qualitative) }, { ...context, intake: qualitative }));
assert.equal(evaluateEvidenceGate(ledger).status, "LIMITED");
ledger.semantic_extractions[0].evidence_items[0].support_verified = false;
assert.equal(evaluateEvidenceGate(ledger).status, "INSUFFICIENT");
ledger.semantic_extractions[0].evidence_items[0].support_verified = true;
ledger.semantic_extractions[0].evidence_basis = "VERIFIED_METADATA_ONLY";
assert.equal(evaluateEvidenceGate(ledger).status, "INSUFFICIENT");
assert.equal(inspectableEvidence(ledger).length, 0, "El consumidor usa la misma elegibilidad que el gate");
ledger.semantic_extractions[0].evidence_basis = "PDF_FULLTEXT";
ledger.semantic_extractions[0].quality_decision = "insufficient";
assert.equal(inspectableEvidence(ledger).length, 0, "Una extraccion declarada insuficiente no alimenta afirmaciones");
console.log("PASS B2 evidence continuity: 22 assertions; availability, provenance, stale selection/intake, sufficient/limited/insufficient, methodological pluralism.");
