import assert from "node:assert/strict";
import { ApplicationBudget, withApplicationBudget, currentApplicationBudget } from "@/server/mvp/application-budget";
import { assessEvidenceCoverage, permitsMethodologicalSupport } from "@/server/mvp/evidence-coverage";
import { parseCitationCandidates, canPromoteCandidate } from "@/server/mvp/citation-chaining";
import { runEvidenceTiers, DEEP_RESEARCH_MAX_USD } from "@/server/mvp/research-fallback";
import { assessAssetQuality } from "@/server/mvp/scientific-assets";
import { normalizeConsistencyMatrix, consistencyTableRows, researchDesignSchema, validateResearchDefinition, MVP_DOCUMENT_SECTIONS } from "@/server/mvp/research-plan-contracts";
import type { MvpStep5EvidenceLedger } from "@/server/mvp/evidence-materialization-types";
import { compactSectionToBudget, paragraphWordCount } from "@/server/mvp/section-budget";

export const definition = { problem: "Problema sintético delimitado", questions: [{ id: "Q1", text: "¿Cómo comprender el fenómeno?", kind: "general" as const }], objectives: [{ id: "O1", text: "Comprender el fenómeno sin anticipar resultados.", question_ids: ["Q1"] }], hypotheses_or_propositions: [] };
export const design = researchDesignSchema.parse({ paradigm: "Interpretativo", approach: "qualitative", design: "Estudio de caso propuesto", unit_population_corpus: "Corpus por delimitar", sampling_selection: "Selección intencional propuesta", constructs: [{ id: "C1", name: "Experiencia", kind: "category", dimensions_indicators: [], operational_definition: "Categoría abierta a revisión" }], data_material_sources: ["Entrevistas propuestas"], techniques: ["Entrevista"], instruments: [], procedure: ["Solicitar consentimiento antes de producir datos"], analysis_method: "Análisis temático propuesto", quality_criteria: ["Reflexividad"], ethical_considerations: ["Consentimiento pendiente"], assumptions: [], limitations: ["Caso único"], pending_decisions: ["Acceso al campo"], methodological_support: [{ source_id: "S1", evidence_id: "E3" }] });
export const matrix = { synthesis: "El diseño vincula la pregunta y el objetivo sin anticipar hallazgos.", rows: [{ question_ids: ["Q1"], objective_ids: ["O1"], construct_ids: ["C1"], design_alignment: "Interpretación del caso", data_techniques_instruments: "Entrevistas propuestas; guía pendiente.", analysis_quality: "Análisis temático y reflexividad.", rationale_evidence: [{ source_id: "S1", evidence_id: "E3" }], pending_decisions: ["Acceso"] }] };
export const ledger = { project_id: "synthetic", source_registry: [{ source_id: "S1", reference_id: "R1", title: "Fuente sintética solo para prueba", authors: ["Ana Ejemplo"], year: 2026, doi: null }], references: [{ reference_id: "R1", formatted_reference: "Ejemplo, A. (2026). Fuente sintética solo para prueba." }], source_assets: [], pdf_materializations: [], semantic_extractions: [{ status: "completed", quality_decision: "usable", evidence_basis: "PDF_FULLTEXT", evidence_items: ["problem_statement", "research_antecedents", "theoretical_framework", "methodology"].map((section_key, i) => ({ source_id: "S1", evidence_id: `E${i}`, section_key, traceable_summary_es: "Extracto sintético verificado únicamente en esta prueba.", supporting_excerpt: "Extracto sintético verificado únicamente en esta prueba.", allowed_use: "theory_or_method_support", support_verified: true })) }] } as unknown as MvpStep5EvidenceLedger;

async function main() {
  assert.equal(MVP_DOCUMENT_SECTIONS.length, 11);
  assert.ok(!MVP_DOCUMENT_SECTIONS.some((s) => /schedule|budget/.test(s)));
  validateResearchDefinition(definition);
  const normalized = normalizeConsistencyMatrix(matrix, definition, design);
  assert.equal(consistencyTableRows(normalized, definition, design)[1][0], `${definition.questions[0].text}\n\n${definition.objectives[0].text}`);
  assert.throws(() => normalizeConsistencyMatrix({ ...matrix, rows: [{ ...matrix.rows[0], objective_ids: ["invented"] }] }, definition, design), /UNKNOWN/);
  assert.throws(() => normalizeConsistencyMatrix({ ...matrix, rows: [] }, definition, design));
  assert.throws(() => validateResearchDefinition({ ...definition, objectives: [{ ...definition.objectives[0], question_ids: ["unknown"] }] }), /MISMATCH/);
  assert.equal(design.constructs[0].kind, "category");
  assert.equal(design.instruments.length, 0);
  assert.doesNotThrow(() => researchDesignSchema.parse({ ...design, approach: "computational", constructs: [{ ...design.constructs[0], kind: "variable" }] }));
  assert.equal(assessEvidenceCoverage(ledger).status, "SUFFICIENT");
  const limited = structuredClone(ledger); limited.semantic_extractions[0].evidence_basis = "ABSTRACT_METADATA";
  assert.equal(assessEvidenceCoverage(limited).status, "LIMITED");
  assert.equal(permitsMethodologicalSupport("context_only"), false);
  assert.equal(permitsMethodologicalSupport("blueprint_planning"), true);
  const contextual = structuredClone(ledger); contextual.semantic_extractions[0].evidence_items.forEach((item) => { item.allowed_use = "context_only"; });
  assert.equal(assessEvidenceCoverage(contextual).status, "INSUFFICIENT");
  const insufficient = structuredClone(ledger); insufficient.semantic_extractions[0].evidence_basis = "VERIFIED_METADATA_ONLY";
  assert.equal(assessEvidenceCoverage(insufficient).status, "INSUFFICIENT");
  const chain = parseCitationCandidates("Texto 10.1234/not-a-reference\nReferencias\n10.1234/abc.\nhttps://doi.org/10.1234/abc\n10.1234/def", "R1");
  assert.deepEqual(chain.map((c) => c.doi), ["10.1234/abc", "10.1234/def"]);
  assert.ok(chain.every((c) => c.status === "DISCOVERY_CANDIDATE"));
  assert.equal(parseCitationCandidates("References\n10.1234/abc", "R1", 2).length, 0);
  assert.equal(parseCitationCandidates("References\n" + Array.from({ length: 30 }, (_, i) => `10.1234/item${i}`).join("\n"), "R1").length, 10);
  assert.equal(canPromoteCandidate({ identityResolved: true, inspected: true, evidenceLevel: "METADATA_ONLY", excerptVerified: true }), false);
  assert.equal(canPromoteCandidate({ identityResolved: true, inspected: true, evidenceLevel: "ABSTRACT_AVAILABLE", excerptVerified: true }), true);
  assert.equal(canPromoteCandidate({ identityResolved: true, inspected: false, evidenceLevel: "FULL_TEXT_MATERIALIZED", excerptVerified: true }), false);
  let calls = 0;
  const runTiers = (status: string, tier2: string, tier3: string) => runEvidenceTiers({ initial: { status }, assess: (v) => v, deterministic: async () => { calls++; return { status: tier2 }; }, deep: async () => { calls++; return { status: tier3 }; } });
  assert.equal((await runTiers("SUFFICIENT", "INSUFFICIENT", "INSUFFICIENT")).blocked, false); assert.equal(calls, 0);
  await runTiers("LIMITED", "INSUFFICIENT", "INSUFFICIENT"); assert.equal(calls, 0);
  assert.equal((await runTiers("INSUFFICIENT", "LIMITED", "INSUFFICIENT")).blocked, false); assert.equal(calls, 1);
  assert.equal((await runTiers("INSUFFICIENT", "INSUFFICIENT", "INSUFFICIENT")).blocked, true); assert.equal(calls, 3);
  const budget = new ApplicationBudget(1);
  budget.reserve("call", "fixture", 0.6).complete(0.1, { input_tokens: 10 });
  assert.throws(() => budget.reserve("blocked", "fixture", 0.91), /BUDGET/);
  budget.reserve("unknown", "fixture", 0.2).fail();
  assert.ok(Math.abs(budget.committedUsd - 0.3) < 1e-8);
  const violated = new ApplicationBudget(1);
  assert.throws(() => violated.reserve("underestimated", "fixture", 0.1).complete(0.2, {}), /BOUND_VIOLATED/);
  assert.throws(() => violated.reserve("must-stop", "fixture", 0.01), /BUDGET_BLOCKED/);
  await withApplicationBudget(budget, async () => assert.equal(currentApplicationBudget(), budget));
  assert.ok(DEEP_RESEARCH_MAX_USD < 2);
  const paragraphs = [{ text: "Contenido repetido de una prueba sintética. ".repeat(20), citations: [{ source_id: "S1", evidence_id: "E1" }] }];
  const compactInput = { provider: { generateStructuredObject: async () => ({ paragraphs: [{ text: "Contenido sintético resumido sin nuevos hechos.", citations: paragraphs[0].citations }] }) } as any, section: "fixture", maxWords: 20, paragraphs, projectId: "synthetic", runId: "synthetic" };
  const compacted = await compactSectionToBudget(compactInput);
  assert.ok(paragraphWordCount(compacted.paragraphs) <= 20);
  assert.deepEqual(compacted.paragraphs[0].citations, paragraphs[0].citations);
  await assert.rejects(compactSectionToBudget({ ...compactInput, provider: { generateStructuredObject: async () => ({ paragraphs: [{ text: "Texto corto", citations: [] }] }) } as any }), /CHANGED_EVIDENCE/);
  const retained = await compactSectionToBudget({ ...compactInput, provider: { generateStructuredObject: async () => ({ paragraphs }) } as any });
  assert.equal(retained.prompt_record?.budget_unresolved, true);
  assert.deepEqual(retained.paragraphs, paragraphs, "A missed editorial target cannot silently truncate scientific content");
  const asset = { coordinates: { status: "exact_bbox", bbox: { x: 50, y: 100, width: 300, height: 160 }, page_width: 600, page_height: 800 }, render_strategy: "layout_crop", body_image_path: "fixture.png", caption_text: "Figura 1. Sintética", asset_kind: "figure", status: "ready_for_review", errors: [], quality_flags: [], warnings: [] } as any;
  assert.equal(assessAssetQuality(asset).accepted, true);
  assert.equal(assessAssetQuality({ ...asset, warnings: ["Region inferred from caption because no native object bbox was available."] }).accepted, false);
  for (const patch of [{ render_strategy: "page_image" }, { caption_text: "" }, { quality_flags: ["clipped"] }, { coordinates: { ...asset.coordinates, bbox: { x: 0, y: 0, width: 600, height: 800 } } }]) assert.equal(assessAssetQuality({ ...asset, ...patch }).accepted, false);
  console.log("PASS B3 contracts: structure, pluralism, strict matrix IDs, coverage, bounded chaining/promotion, tier triggers, costs and crop rejection.");
}
if (process.argv[1]?.endsWith("test-b3-scientific-contracts.ts")) main().catch((error) => { console.error(error); process.exitCode = 1; });
