import { createHash } from "node:crypto";
import { mkdir, open, rename, unlink, stat } from "node:fs/promises";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { PdfUploadError, type PdfSafeDiagnostics } from "./pdf-upload-error";

export interface ArtifactStore {
  putPdf(key: string, stream: ReadableStream<Uint8Array>, expectedBytes: number): Promise<{ byteSize: number; sha256: string }>;
  exists(key: string): Promise<boolean>;
}

// Private append-only keys, generated by server. No public/static mapping.
export class PrivateFileArtifactStore implements ArtifactStore {
  constructor(readonly root = process.env.IMX_PRIVATE_STORAGE_ROOT || path.resolve("artifacts-local/private-storage")) {}
  private file(key: string) {
    if (!/^[a-f0-9-]{36}$/.test(key)) throw new Error("INVALID_STORAGE_KEY");
    return path.join(this.root, `${key}.pdf`);
  }
  pathForPdf(key: string) { return this.file(key); }
  async exists(key: string) { try { return (await stat(this.file(key))).isFile(); } catch { return false; } }
  async putPdf(key: string, stream: ReadableStream<Uint8Array>, expectedBytes: number) {
    const destination = this.file(key), temporary = `${destination}.part`;
    const reader = stream.getReader(), hash = createHash("sha256");
    let byteSize = 0, prefix = Buffer.alloc(0), stage = "STORAGE_OPEN";
    let diagnostics: PdfSafeDiagnostics = {};
    let file: Awaited<ReturnType<typeof open>> | undefined;
    try {
      await mkdir(this.root, { recursive: true, mode: 0o700 });
      if (await this.exists(key)) throw new Error("STORAGE_KEY_EXISTS");
      file = await open(temporary, "wx", 0o600);
      stage = "BODY_READ";
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        byteSize += value.byteLength;
        if (byteSize > expectedBytes) throw new PdfUploadError("BODY_LENGTH_MISMATCH", expectedBytes, byteSize, stage);
        if (prefix.length < 5) prefix = Buffer.concat([prefix, Buffer.from(value)]).subarray(0, 5);
        hash.update(value);
        stage = "STORAGE_WRITE";
        await file.writeFile(value);
        stage = "BODY_READ";
      }
      if (byteSize !== expectedBytes) throw new PdfUploadError("BODY_LENGTH_MISMATCH", expectedBytes, byteSize, stage);
      if (prefix.toString() !== "%PDF-") throw new PdfUploadError("INVALID_PDF_SIGNATURE", expectedBytes, byteSize, "SIGNATURE");
      stage = "STORAGE_SYNC";
      await file.sync(); await file.close();
      stage = "PDFINFO";
      diagnostics = { inputSha256: hash.copy().digest("hex") };
      // Parser validation is NOT malware/relevance approval. Remains quarantined.
      let stdout: string;
      try {
        ({ stdout } = await promisify(execFile)("pdfinfo", [temporary], { timeout: 15_000, maxBuffer: 65536, encoding: "utf8", env: { PATH: process.env.PATH, LANG: "C", NODE_ENV: process.env.NODE_ENV } }));
      } catch (error) {
        const failure = error as NodeJS.ErrnoException & { signal?: string; killed?: boolean };
        diagnostics = { ...diagnostics, processExitCode: typeof failure.code === "number" ? failure.code : null,
          processSignal: typeof failure.signal === "string" ? failure.signal : null,
          timedOut: Boolean(failure.killed && failure.signal),
          maxBufferExceeded: failure.code === "ERR_CHILD_PROCESS_STDIO_MAXBUFFER" };
        throw new PdfUploadError("PDFINFO_VALIDATION_FAILED", expectedBytes, byteSize, stage, diagnostics);
      }
      const pages = Number(/^Pages:\s+(\d+)/m.exec(stdout)?.[1]);
      diagnostics = { ...diagnostics, pages: Number.isFinite(pages) ? pages : null,
        encrypted: /^Encrypted:\s+yes/m.test(stdout) };
      if (!pages || pages > 1000 || diagnostics.encrypted) throw new PdfUploadError("PDFINFO_VALIDATION_FAILED", expectedBytes, byteSize, stage, diagnostics);
      stage = "STORAGE_RENAME";
      await rename(temporary, destination);
      return { byteSize, sha256: hash.digest("hex") };
    } catch (error) {
      await reader.cancel().catch(() => {}); await file?.close().catch(() => {});
      if (file) await unlink(temporary).catch(() => {});
      throw error instanceof PdfUploadError ? error : new PdfUploadError(stage === "PDFINFO" ? "PDFINFO_VALIDATION_FAILED"
        : stage.startsWith("STORAGE_") ? "PRIVATE_STORAGE_WRITE_FAILED" : "OTHER_SAFE_CATEGORY", expectedBytes, byteSize, stage, diagnostics);
    } finally { reader.releaseLock(); }
  }
}
