import { createHash } from "node:crypto";
import { mkdir, open, rename, unlink, stat } from "node:fs/promises";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

export interface ArtifactStore {
  putPdf(key: string, stream: ReadableStream<Uint8Array>, expectedBytes: number): Promise<{ byteSize: number; sha256: string }>;
  exists(key: string): Promise<boolean>;
}

// Private append-only keys, generated by server. No public/static mapping.
export class PrivateFileArtifactStore implements ArtifactStore {
  constructor(readonly root = process.env.IMX_PRIVATE_STORAGE_ROOT || path.resolve("artifacts-local/private-storage")) {}
  private file(key: string) {
    if (!/^[a-f0-9-]{36}$/.test(key)) throw new Error("INVALID_STORAGE_KEY");
    return path.join(this.root, `${key}.pdf`);
  }
  async exists(key: string) { try { return (await stat(this.file(key))).isFile(); } catch { return false; } }
  async putPdf(key: string, stream: ReadableStream<Uint8Array>, expectedBytes: number) {
    await mkdir(this.root, { recursive: true, mode: 0o700 });
    const destination = this.file(key), temporary = `${destination}.part`;
    if (await this.exists(key)) throw new Error("STORAGE_KEY_EXISTS");
    const file = await open(temporary, "wx", 0o600);
    const reader = stream.getReader(), hash = createHash("sha256");
    let byteSize = 0, prefix = Buffer.alloc(0);
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        byteSize += value.byteLength;
        if (byteSize > expectedBytes) throw new Error("UPLOAD_TOO_LARGE");
        if (prefix.length < 5) prefix = Buffer.concat([prefix, Buffer.from(value)]).subarray(0, 5);
        hash.update(value);
        await file.writeFile(value);
      }
      if (byteSize !== expectedBytes || prefix.toString() !== "%PDF-") throw new Error("INVALID_PDF");
      await file.sync(); await file.close();
      // Parser validation is NOT malware/relevance approval. Remains quarantined.
      const { stdout } = await promisify(execFile)("pdfinfo", [temporary], { timeout: 15_000, maxBuffer: 65536, encoding: "utf8", env: { PATH: process.env.PATH, LANG: "C", NODE_ENV: process.env.NODE_ENV } });
      const pages = Number(/^Pages:\s+(\d+)/m.exec(stdout)?.[1]);
      if (!pages || pages > 1000 || /^Encrypted:\s+yes/m.test(stdout)) throw new Error("UNSUPPORTED_PDF");
      await rename(temporary, destination);
      return { byteSize, sha256: hash.digest("hex") };
    } catch (error) {
      await reader.cancel().catch(() => {}); await file.close().catch(() => {}); await unlink(temporary).catch(() => {});
      throw error;
    } finally { reader.releaseLock(); }
  }
}
